<?php /* Smarty version Smarty-3.1-DEV, created on 2013-05-28 04:09:40
         compiled from "D:\wamp\www\mlpnwrp_tw\public\templates\fgal_context_menu.tpl" */ ?>
<?php /*%%SmartyHeaderCode:2040351a42e04acc038-54935740%%*/if(!defined('SMARTY_DIR')) exit('no direct access allowed');
$_valid = $_smarty_tpl->decodeProperties(array (
  'file_dependency' => 
  array (
    '9334a23809a2ba91489486cada149485c36582f4' => 
    array (
      0 => 'D:\\wamp\\www\\mlpnwrp_tw\\public\\templates\\fgal_context_menu.tpl',
      1 => 1347858119,
      2 => 'file',
    ),
  ),
  'nocache_hash' => '2040351a42e04acc038-54935740',
  'function' => 
  array (
  ),
  'variables' => 
  array (
    'changes' => 0,
    'files' => 0,
    'menu_text' => 0,
    'menu_icon' => 0,
    'user' => 0,
    'filegals_manager' => 0,
    'prefs' => 0,
    'virtual_path' => 0,
    'gal_info' => 0,
    'download_path' => 0,
    'replace_action_title' => 0,
    'view' => 0,
    'tiki_p_share' => 0,
    'tikiroot' => 0,
    'tiki_p_tell_a_friend' => 0,
  ),
  'has_nocache_code' => false,
  'version' => 'Smarty-3.1-DEV',
  'unifunc' => 'content_51a42e053d1db7_85794327',
),false); /*/%%SmartyHeaderCode%%*/?>
<?php if ($_valid && !is_callable('content_51a42e053d1db7_85794327')) {function content_51a42e053d1db7_85794327($_smarty_tpl) {?><?php if (!is_callable('smarty_block_self_link')) include 'lib/smarty_tiki\\block.self_link.php';
if (!is_callable('smarty_function_icon')) include 'lib/smarty_tiki\\function.icon.php';
if (!is_callable('smarty_modifier_virtual_path')) include 'lib/smarty_tiki\\modifier.virtual_path.php';
if (!is_callable('smarty_modifier_truncate')) include 'lib/smarty_tiki\\modifier.truncate.php';
if (!is_callable('smarty_modifier_sefurl')) include 'lib/smarty_tiki\\modifier.sefurl.php';
?>
<?php if ($_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['isgal']==1){?><?php if ($_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['perms']['tiki_p_view_file_gallery']=='y'){?><?php $_smarty_tpl->smarty->_tag_stack[] = array('self_link', array('_icon'=>'folder_go','_menu_text'=>$_smarty_tpl->tpl_vars['menu_text']->value,'_menu_icon'=>$_smarty_tpl->tpl_vars['menu_icon']->value,'galleryId'=>$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['id'])); $_block_repeat=true; echo smarty_block_self_link(array('_icon'=>'folder_go','_menu_text'=>$_smarty_tpl->tpl_vars['menu_text']->value,'_menu_icon'=>$_smarty_tpl->tpl_vars['menu_icon']->value,'galleryId'=>$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['id']), null, $_smarty_tpl, $_block_repeat);while ($_block_repeat) { ob_start();?>
Go to<?php $_block_content = ob_get_clean(); $_block_repeat=false; echo smarty_block_self_link(array('_icon'=>'folder_go','_menu_text'=>$_smarty_tpl->tpl_vars['menu_text']->value,'_menu_icon'=>$_smarty_tpl->tpl_vars['menu_icon']->value,'galleryId'=>$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['id']), $_block_content, $_smarty_tpl, $_block_repeat);  } array_pop($_smarty_tpl->smarty->_tag_stack);?>
<?php }?><?php if ($_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['perms']['tiki_p_create_file_galleries']=='y'){?><?php $_smarty_tpl->smarty->_tag_stack[] = array('self_link', array('_icon'=>'page_edit','_menu_text'=>$_smarty_tpl->tpl_vars['menu_text']->value,'_menu_icon'=>$_smarty_tpl->tpl_vars['menu_icon']->value,'edit_mode'=>1,'galleryId'=>$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['id'])); $_block_repeat=true; echo smarty_block_self_link(array('_icon'=>'page_edit','_menu_text'=>$_smarty_tpl->tpl_vars['menu_text']->value,'_menu_icon'=>$_smarty_tpl->tpl_vars['menu_icon']->value,'edit_mode'=>1,'galleryId'=>$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['id']), null, $_smarty_tpl, $_block_repeat);while ($_block_repeat) { ob_start();?>
Properties<?php $_block_content = ob_get_clean(); $_block_repeat=false; echo smarty_block_self_link(array('_icon'=>'page_edit','_menu_text'=>$_smarty_tpl->tpl_vars['menu_text']->value,'_menu_icon'=>$_smarty_tpl->tpl_vars['menu_icon']->value,'edit_mode'=>1,'galleryId'=>$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['id']), $_block_content, $_smarty_tpl, $_block_repeat);  } array_pop($_smarty_tpl->smarty->_tag_stack);?>
<?php }?><?php if ($_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['perms']['tiki_p_upload_files']=='y'&&($_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['perms']['tiki_p_admin_file_galleries']=='y'||($_smarty_tpl->tpl_vars['user']->value&&$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['user']==$_smarty_tpl->tpl_vars['user']->value)||$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['public']=='y')){?><a href="tiki-upload_file.php?galleryId=<?php echo $_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['id'];?>
<?php if (!empty($_smarty_tpl->tpl_vars['filegals_manager']->value)){?>&amp;filegals_manager=<?php echo htmlspecialchars($_smarty_tpl->tpl_vars['filegals_manager']->value, ENT_QUOTES, 'UTF-8', true);?>
<?php }?>"><?php echo smarty_function_icon(array('_menu_text'=>$_smarty_tpl->tpl_vars['menu_text']->value,'_menu_icon'=>$_smarty_tpl->tpl_vars['menu_icon']->value,'_id'=>'upload'),$_smarty_tpl);?>
</a><?php }?><?php if ($_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['perms']['tiki_p_assign_perm_file_gallery']=='y'){?><a href="tiki-objectpermissions.php?objectName=<?php echo rawurlencode($_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['name']);?>
&amp;objectType=file+gallery&amp;permType=file+galleries&amp;objectId=<?php echo $_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['id'];?>
<?php if (!empty($_smarty_tpl->tpl_vars['filegals_manager']->value)){?>&amp;filegals_manager=<?php echo htmlspecialchars($_smarty_tpl->tpl_vars['filegals_manager']->value, ENT_QUOTES, 'UTF-8', true);?>
<?php }?>"><?php if ($_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['public']!='y'){?><?php echo smarty_function_icon(array('_menu_text'=>$_smarty_tpl->tpl_vars['menu_text']->value,'_menu_icon'=>$_smarty_tpl->tpl_vars['menu_icon']->value,'_id'=>'key_private','alt'=>"Private Gallery"),$_smarty_tpl);?>
<?php }elseif($_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['perms']['has_special_perm']=='y'){?><?php echo smarty_function_icon(array('_menu_text'=>$_smarty_tpl->tpl_vars['menu_text']->value,'_menu_icon'=>$_smarty_tpl->tpl_vars['menu_icon']->value,'_id'=>'key_active','alt'=>"Active Perms"),$_smarty_tpl);?>
<?php }else{ ?><?php echo smarty_function_icon(array('_menu_text'=>$_smarty_tpl->tpl_vars['menu_text']->value,'_menu_icon'=>$_smarty_tpl->tpl_vars['menu_icon']->value,'_id'=>'key','alt'=>"Perms"),$_smarty_tpl);?>
<?php }?></a><?php }?><?php if ($_smarty_tpl->tpl_vars['prefs']->value['feature_webdav']=='y'){?><?php $_smarty_tpl->tpl_vars['virtual_path'] = new Smarty_variable(smarty_modifier_virtual_path($_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['id'],'filegal'), null, 0);?><a style="behavior: url(#default#AnchorClick);" href="<?php echo $_smarty_tpl->tpl_vars['virtual_path']->value;?>
" folder="<?php echo $_smarty_tpl->tpl_vars['virtual_path']->value;?>
"><?php echo smarty_function_icon(array('_id'=>"tree_folder_open"),$_smarty_tpl);?>
Open as WebFolder</a><?php }?><?php if ($_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['perms']['tiki_p_create_file_galleries']=='y'){?><?php $_smarty_tpl->smarty->_tag_stack[] = array('self_link', array('_icon'=>'cross','_menu_text'=>$_smarty_tpl->tpl_vars['menu_text']->value,'_menu_icon'=>$_smarty_tpl->tpl_vars['menu_icon']->value,'removegal'=>$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['id'])); $_block_repeat=true; echo smarty_block_self_link(array('_icon'=>'cross','_menu_text'=>$_smarty_tpl->tpl_vars['menu_text']->value,'_menu_icon'=>$_smarty_tpl->tpl_vars['menu_icon']->value,'removegal'=>$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['id']), null, $_smarty_tpl, $_block_repeat);while ($_block_repeat) { ob_start();?>
Delete<?php $_block_content = ob_get_clean(); $_block_repeat=false; echo smarty_block_self_link(array('_icon'=>'cross','_menu_text'=>$_smarty_tpl->tpl_vars['menu_text']->value,'_menu_icon'=>$_smarty_tpl->tpl_vars['menu_icon']->value,'removegal'=>$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['id']), $_block_content, $_smarty_tpl, $_block_repeat);  } array_pop($_smarty_tpl->smarty->_tag_stack);?>
<?php }?><?php }else{ ?><?php if ($_smarty_tpl->tpl_vars['prefs']->value['javascript_enabled']=='y'){?><?php if ($_smarty_tpl->tpl_vars['menu_text']->value=='y'||$_smarty_tpl->tpl_vars['menu_icon']->value=='y'){?><form class="upform" name="form<?php echo $_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['fileId'];?>
" method="post" action="tiki-list_file_gallery.php?galleryId=<?php echo $_smarty_tpl->tpl_vars['gal_info']->value['galleryId'];?>
<?php if (!empty($_smarty_tpl->tpl_vars['filegals_manager']->value)){?>&amp;filegals_manager=<?php echo htmlspecialchars($_smarty_tpl->tpl_vars['filegals_manager']->value, ENT_QUOTES, 'UTF-8', true);?>
<?php }?><?php if ($_smarty_tpl->tpl_vars['prefs']->value['fgal_asynchronous_indexing']=='y'){?>&amp;fast<?php }?>" enctype="multipart/form-data"><?php }?><?php if ($_smarty_tpl->tpl_vars['menu_text']->value!='y'){?><div style="float:left"><?php }?><?php }?><?php if (smarty_modifier_truncate($_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['type'],6,'',true)=='image/'){?><a href="<?php echo smarty_modifier_sefurl($_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['id'],'display');?>
"><?php echo smarty_function_icon(array('_id'=>'magnifier','_menu_text'=>$_smarty_tpl->tpl_vars['menu_text']->value,'_menu_icon'=>$_smarty_tpl->tpl_vars['menu_icon']->value,'alt'=>"Display"),$_smarty_tpl);?>
</a><?php if ($_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['perms']['tiki_p_upload_files']=='y'&&$_smarty_tpl->tpl_vars['prefs']->value['feature_draw']=='y'){?><?php if ($_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['type']=='image/svg+xml'||$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['type']=='image/jpeg'||$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['type']=='image/gif'||$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['type']=='image/png'||$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['type']=='image/tiff'){?><a class="draw dialog" data-name="<?php echo $_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['filename'];?>
" title="Edit: <?php echo $_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['filename'];?>
" href="tiki-edit_draw.php?fileId=<?php echo $_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['id'];?>
&galleryId=<?php echo $_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['galleryId'];?>
" data-fileid='<?php echo $_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['id'];?>
' data-galleryid='<?php echo $_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['galleryId'];?>
' onclick='return $(this).ajaxEditDraw();'><?php echo smarty_function_icon(array('_id'=>'page_edit','_menu_text'=>$_smarty_tpl->tpl_vars['menu_text']->value,'_menu_icon'=>$_smarty_tpl->tpl_vars['menu_icon']->value,'alt'=>"Edit"),$_smarty_tpl);?>
</a><?php }?><?php }?><?php }elseif($_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['type']=='text/csv'&&$_smarty_tpl->tpl_vars['prefs']->value['feature_sheet']=='y'){?><a href="tiki-view_sheets.php?fileId=<?php echo $_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['id'];?>
"><?php echo smarty_function_icon(array('_id'=>'magnifier','_menu_text'=>$_smarty_tpl->tpl_vars['menu_text']->value,'_menu_icon'=>$_smarty_tpl->tpl_vars['menu_icon']->value,'alt'=>"Display"),$_smarty_tpl);?>
</a><?php }elseif(($_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['type']=='application/vnd.oasis.opendocument.text'||$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['type']=='application/octet-stream')&&$_smarty_tpl->tpl_vars['prefs']->value['feature_docs']=='y'){?><a href="tiki-edit_docs.php?fileId=<?php echo $_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['id'];?>
"><?php echo smarty_function_icon(array('_id'=>'magnifier','_menu_text'=>$_smarty_tpl->tpl_vars['menu_text']->value,'_menu_icon'=>$_smarty_tpl->tpl_vars['menu_icon']->value,'alt'=>"Display"),$_smarty_tpl);?>
</a><?php if ($_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['perms']['tiki_p_upload_files']=='y'){?><a href="tiki-edit_docs.php?fileId=<?php echo $_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['id'];?>
&edit"><?php echo smarty_function_icon(array('_id'=>'page_edit','_menu_text'=>$_smarty_tpl->tpl_vars['menu_text']->value,'_menu_icon'=>$_smarty_tpl->tpl_vars['menu_icon']->value,'alt'=>"Edit"),$_smarty_tpl);?>
</a><?php }?><?php }?><?php if ((isset($_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['p_download_files'])&&$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['p_download_files']=='y')||(!isset($_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['p_download_files'])&&$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['perms']['tiki_p_download_files']=='y')){?><?php if ($_smarty_tpl->tpl_vars['gal_info']->value['type']=='podcast'||$_smarty_tpl->tpl_vars['gal_info']->value['type']=='vidcast'){?><a href="<?php echo $_smarty_tpl->tpl_vars['download_path']->value;?>
<?php echo $_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['path'];?>
"><?php }else{ ?><a href="<?php echo smarty_modifier_sefurl($_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['id'],'file');?>
"><?php }?><?php if ($_smarty_tpl->tpl_vars['prefs']->value['feature_file_galleries_save_draft']=='y'&&$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['nbDraft']>0){?><?php $_smarty_tpl->tpl_vars['download_action_title'] = new Smarty_variable("Download current version", null, 0);?><?php }else{ ?><?php $_smarty_tpl->tpl_vars['download_action_title'] = new Smarty_variable("Download", null, 0);?><?php }?><?php echo smarty_function_icon(array('_menu_text'=>$_smarty_tpl->tpl_vars['menu_text']->value,'_menu_icon'=>$_smarty_tpl->tpl_vars['menu_icon']->value,'_id'=>'disk','alt'=>((string)$_smarty_tpl->tpl_vars['download_action_title']->value)),$_smarty_tpl);?>
</a><?php }?><?php if ($_smarty_tpl->tpl_vars['gal_info']->value['archives']>-1){?><?php if (isset($_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['nbArchives'])&&$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['nbArchives']>0){?><?php $_smarty_tpl->tpl_vars['nb_archives'] = new Smarty_variable($_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['nbArchives'], null, 0);?><a href="tiki-file_archives.php?fileId=<?php echo $_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['fileId'];?>
<?php if (!empty($_smarty_tpl->tpl_vars['filegals_manager']->value)){?>&amp;filegals_manager=<?php echo htmlspecialchars($_smarty_tpl->tpl_vars['filegals_manager']->value, ENT_QUOTES, 'UTF-8', true);?>
<?php }?>"><?php echo smarty_function_icon(array('_menu_text'=>$_smarty_tpl->tpl_vars['menu_text']->value,'_menu_icon'=>$_smarty_tpl->tpl_vars['menu_icon']->value,'_id'=>'disk_multiple','alt'=>"Archives (".((string)$_smarty_tpl->tpl_vars['nb_archives']->value).")"),$_smarty_tpl);?>
</a><?php }else{ ?><?php echo smarty_function_icon(array('_menu_text'=>$_smarty_tpl->tpl_vars['menu_text']->value,'_menu_icon'=>$_smarty_tpl->tpl_vars['menu_icon']->value,'_id'=>'disk_multiple_gray','alt'=>"Archives"),$_smarty_tpl);?>
<?php }?><?php $_smarty_tpl->tpl_vars['replace_action_title'] = new Smarty_variable("Upload New Version", null, 0);?><?php }else{ ?><?php $_smarty_tpl->tpl_vars['replace_action_title'] = new Smarty_variable("Replace", null, 0);?><?php }?><?php if ($_smarty_tpl->tpl_vars['prefs']->value['feature_file_galleries_save_draft']=='y'){?><?php if ($_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['nbDraft']>0){?><?php $_smarty_tpl->tpl_vars['replace_action_title'] = new Smarty_variable("Replace your draft", null, 0);?><?php }else{ ?><?php $_smarty_tpl->tpl_vars['replace_action_title'] = new Smarty_variable("Upload your draft", null, 0);?><?php }?><?php }?><?php if ($_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['perms']['tiki_p_admin_file_galleries']=='y'||($_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['lockedby']&&$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['lockedby']==$_smarty_tpl->tpl_vars['user']->value)||(!$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['lockedby']&&(($_smarty_tpl->tpl_vars['user']->value&&$_smarty_tpl->tpl_vars['user']->value==$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['user'])||$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['perms']['tiki_p_edit_gallery_file']=='y'))){?><?php if ($_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['archiveId']==0){?><?php if ($_smarty_tpl->tpl_vars['prefs']->value['feature_file_galleries_save_draft']=='y'&&$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['nbDraft']>0){?><?php $_smarty_tpl->smarty->_tag_stack[] = array('self_link', array('_icon'=>'accept','_menu_text'=>$_smarty_tpl->tpl_vars['menu_text']->value,'_menu_icon'=>$_smarty_tpl->tpl_vars['menu_icon']->value,'validate'=>$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['fileId'],'galleryId'=>$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['galleryId'])); $_block_repeat=true; echo smarty_block_self_link(array('_icon'=>'accept','_menu_text'=>$_smarty_tpl->tpl_vars['menu_text']->value,'_menu_icon'=>$_smarty_tpl->tpl_vars['menu_icon']->value,'validate'=>$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['fileId'],'galleryId'=>$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['galleryId']), null, $_smarty_tpl, $_block_repeat);while ($_block_repeat) { ob_start();?>
Validate your draft<?php $_block_content = ob_get_clean(); $_block_repeat=false; echo smarty_block_self_link(array('_icon'=>'accept','_menu_text'=>$_smarty_tpl->tpl_vars['menu_text']->value,'_menu_icon'=>$_smarty_tpl->tpl_vars['menu_icon']->value,'validate'=>$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['fileId'],'galleryId'=>$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['galleryId']), $_block_content, $_smarty_tpl, $_block_repeat);  } array_pop($_smarty_tpl->smarty->_tag_stack);?>
<?php $_smarty_tpl->smarty->_tag_stack[] = array('self_link', array('_icon'=>'cross','_menu_text'=>$_smarty_tpl->tpl_vars['menu_text']->value,'_menu_icon'=>$_smarty_tpl->tpl_vars['menu_icon']->value,'draft'=>'remove','remove'=>$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['fileId'],'galleryId'=>$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['galleryId'])); $_block_repeat=true; echo smarty_block_self_link(array('_icon'=>'cross','_menu_text'=>$_smarty_tpl->tpl_vars['menu_text']->value,'_menu_icon'=>$_smarty_tpl->tpl_vars['menu_icon']->value,'draft'=>'remove','remove'=>$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['fileId'],'galleryId'=>$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['galleryId']), null, $_smarty_tpl, $_block_repeat);while ($_block_repeat) { ob_start();?>
Delete your draft<?php $_block_content = ob_get_clean(); $_block_repeat=false; echo smarty_block_self_link(array('_icon'=>'cross','_menu_text'=>$_smarty_tpl->tpl_vars['menu_text']->value,'_menu_icon'=>$_smarty_tpl->tpl_vars['menu_icon']->value,'draft'=>'remove','remove'=>$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['fileId'],'galleryId'=>$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['galleryId']), $_block_content, $_smarty_tpl, $_block_repeat);  } array_pop($_smarty_tpl->smarty->_tag_stack);?>
<?php }?><?php if ($_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['perms']['tiki_p_admin_file_galleries']=='y'||empty($_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['locked'])||(isset($_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['locked'])&&$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['locked']&&$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['lockedby']==$_smarty_tpl->tpl_vars['user']->value)||$_smarty_tpl->tpl_vars['gal_info']->value['lockable']!='y'){?><?php if ($_smarty_tpl->tpl_vars['prefs']->value['javascript_enabled']=='y'){?><?php if ($_smarty_tpl->tpl_vars['menu_text']->value!='y'){?></div><?php }?><?php if ($_smarty_tpl->tpl_vars['prefs']->value['fgal_display_replace']=='y'){?><div class="upspan <?php if ($_smarty_tpl->tpl_vars['menu_text']->value=='y'){?>upspantext<?php }?>" style="display: inline; position:relative<?php if ($_smarty_tpl->tpl_vars['menu_text']->value=='y'){?>; position:absolute<?php }else{ ?>; float:left<?php }?>; overflow:hidden" title="<?php echo $_smarty_tpl->tpl_vars['replace_action_title']->value;?>
"><input type="file" style="position:absolute; z-index:1001; right:0; top:0; font-size:600px; opacity:0; -moz-opacity:0; filter:alpha(opacity=0); cursor:pointer" name="upfile<?php echo $_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['id'];?>
" onchange="this.form.submit(); return false;"/><input type="hidden" name="fileId" value="<?php echo $_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['fileId'];?>
" /><a href="#"><?php echo smarty_function_icon(array('_menu_text'=>$_smarty_tpl->tpl_vars['menu_text']->value,'_menu_icon'=>$_smarty_tpl->tpl_vars['menu_icon']->value,'_id'=>'database_refresh','alt'=>$_smarty_tpl->tpl_vars['replace_action_title']->value),$_smarty_tpl);?>
</a></div><?php if ($_smarty_tpl->tpl_vars['menu_text']->value=='y'){?><a style="visibility: hidden"><?php echo smarty_function_icon(array('_menu_text'=>$_smarty_tpl->tpl_vars['menu_text']->value,'_menu_icon'=>$_smarty_tpl->tpl_vars['menu_icon']->value,'_id'=>'database_refresh','alt'=>$_smarty_tpl->tpl_vars['replace_action_title']->value),$_smarty_tpl);?>
</a><?php }?><?php }?><?php }else{ ?><a href="tiki-upload_file.php?galleryId=<?php echo $_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['galleryId'];?>
&amp;fileId=<?php echo $_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['id'];?>
<?php if (!empty($_smarty_tpl->tpl_vars['filegals_manager']->value)){?>&amp;filegals_manager=<?php echo htmlspecialchars($_smarty_tpl->tpl_vars['filegals_manager']->value, ENT_QUOTES, 'UTF-8', true);?>
<?php }?>"><?php echo smarty_function_icon(array('_menu_text'=>$_smarty_tpl->tpl_vars['menu_text']->value,'_menu_icon'=>$_smarty_tpl->tpl_vars['menu_icon']->value,'_id'=>'database_refresh','alt'=>"Upload New Version"),$_smarty_tpl);?>
</a><?php }?><?php if ($_smarty_tpl->tpl_vars['prefs']->value['fgal_display_properties']=='y'){?><a href="tiki-list_file_gallery.php?galleryId=<?php echo $_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['galleryId'];?>
&fileId=<?php echo $_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['id'];?>
&view=page"><?php echo smarty_function_icon(array('_menu_text'=>$_smarty_tpl->tpl_vars['menu_text']->value,'_menu_icon'=>$_smarty_tpl->tpl_vars['menu_icon']->value,'_id'=>'table','alt'=>"Page View"),$_smarty_tpl);?>
</a><a href="tiki-upload_file.php?galleryId=<?php echo $_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['galleryId'];?>
&amp;fileId=<?php echo $_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['id'];?>
<?php if (!empty($_smarty_tpl->tpl_vars['filegals_manager']->value)){?>&amp;filegals_manager=<?php echo htmlspecialchars($_smarty_tpl->tpl_vars['filegals_manager']->value, ENT_QUOTES, 'UTF-8', true);?>
<?php }?>"><?php echo smarty_function_icon(array('_menu_text'=>$_smarty_tpl->tpl_vars['menu_text']->value,'_menu_icon'=>$_smarty_tpl->tpl_vars['menu_icon']->value,'_id'=>'page_edit','alt'=>"Edit Properties"),$_smarty_tpl);?>
</a><a href="tiki-list_file_gallery.php?galleryId=<?php echo $_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['galleryId'];?>
&fileId=<?php echo $_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['id'];?>
&action=refresh_metadata<?php if (isset($_smarty_tpl->tpl_vars['view']->value)){?>&view=<?php echo $_smarty_tpl->tpl_vars['view']->value;?>
<?php }?>"><?php echo smarty_function_icon(array('_menu_text'=>$_smarty_tpl->tpl_vars['menu_text']->value,'_menu_icon'=>$_smarty_tpl->tpl_vars['menu_icon']->value,'_id'=>'tag_green','alt'=>"Refresh Metadata"),$_smarty_tpl);?>
</a><?php }?><?php }?><?php if ($_smarty_tpl->tpl_vars['gal_info']->value['lockable']=='y'&&$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['isgal']!=1){?><?php if ($_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['lockedby']){?><?php $_smarty_tpl->smarty->_tag_stack[] = array('self_link', array('_icon'=>'lock_delete','_menu_text'=>$_smarty_tpl->tpl_vars['menu_text']->value,'_menu_icon'=>$_smarty_tpl->tpl_vars['menu_icon']->value,'lock'=>'n','fileId'=>$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['fileId'],'galleryId'=>$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['galleryId'])); $_block_repeat=true; echo smarty_block_self_link(array('_icon'=>'lock_delete','_menu_text'=>$_smarty_tpl->tpl_vars['menu_text']->value,'_menu_icon'=>$_smarty_tpl->tpl_vars['menu_icon']->value,'lock'=>'n','fileId'=>$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['fileId'],'galleryId'=>$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['galleryId']), null, $_smarty_tpl, $_block_repeat);while ($_block_repeat) { ob_start();?>
Unlock<?php $_block_content = ob_get_clean(); $_block_repeat=false; echo smarty_block_self_link(array('_icon'=>'lock_delete','_menu_text'=>$_smarty_tpl->tpl_vars['menu_text']->value,'_menu_icon'=>$_smarty_tpl->tpl_vars['menu_icon']->value,'lock'=>'n','fileId'=>$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['fileId'],'galleryId'=>$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['galleryId']), $_block_content, $_smarty_tpl, $_block_repeat);  } array_pop($_smarty_tpl->smarty->_tag_stack);?>
<?php }else{ ?><?php if ((isset($_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['p_download_files'])&&$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['p_download_files']=='y')||(!isset($_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['p_download_files'])&&$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['perms']['tiki_p_download_files']=='y')){?><?php if ($_smarty_tpl->tpl_vars['prefs']->value['javascript_enabled']=='y'){?><a href="#" onclick="window.open('<?php echo smarty_modifier_sefurl($_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['fileId'],'file');?>
&lock=y'); document.location.href = '<?php $_smarty_tpl->smarty->_tag_stack[] = array('self_link', array('_type'=>'absolute_uri','_tag'=>'n','fileId'=>$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['fileId'],'lock'=>'y','galleryId'=>$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['galleryId'])); $_block_repeat=true; echo smarty_block_self_link(array('_type'=>'absolute_uri','_tag'=>'n','fileId'=>$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['fileId'],'lock'=>'y','galleryId'=>$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['galleryId']), null, $_smarty_tpl, $_block_repeat);while ($_block_repeat) { ob_start();?>
<?php $_block_content = ob_get_clean(); $_block_repeat=false; echo smarty_block_self_link(array('_type'=>'absolute_uri','_tag'=>'n','fileId'=>$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['fileId'],'lock'=>'y','galleryId'=>$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['galleryId']), $_block_content, $_smarty_tpl, $_block_repeat);  } array_pop($_smarty_tpl->smarty->_tag_stack);?>
'; return false;"><?php echo smarty_function_icon(array('_menu_text'=>$_smarty_tpl->tpl_vars['menu_text']->value,'_menu_icon'=>$_smarty_tpl->tpl_vars['menu_icon']->value,'_id'=>'disk_lock','alt'=>"Download and lock"),$_smarty_tpl);?>
</a><?php }else{ ?><a href="<?php echo smarty_modifier_sefurl($_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['fileId'],'file');?>
&amp;lock=y"><?php echo smarty_function_icon(array('_menu_text'=>$_smarty_tpl->tpl_vars['menu_text']->value,'_menu_icon'=>$_smarty_tpl->tpl_vars['menu_icon']->value,'_id'=>'disk_lock','alt'=>"Download and lock"),$_smarty_tpl);?>
</a><?php }?><?php }?><?php $_smarty_tpl->smarty->_tag_stack[] = array('self_link', array('_icon'=>'lock_add','_menu_text'=>$_smarty_tpl->tpl_vars['menu_text']->value,'_menu_icon'=>$_smarty_tpl->tpl_vars['menu_icon']->value,'lock'=>'y','fileId'=>$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['fileId'],'galleryId'=>$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['galleryId'])); $_block_repeat=true; echo smarty_block_self_link(array('_icon'=>'lock_add','_menu_text'=>$_smarty_tpl->tpl_vars['menu_text']->value,'_menu_icon'=>$_smarty_tpl->tpl_vars['menu_icon']->value,'lock'=>'y','fileId'=>$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['fileId'],'galleryId'=>$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['galleryId']), null, $_smarty_tpl, $_block_repeat);while ($_block_repeat) { ob_start();?>
Lock<?php $_block_content = ob_get_clean(); $_block_repeat=false; echo smarty_block_self_link(array('_icon'=>'lock_add','_menu_text'=>$_smarty_tpl->tpl_vars['menu_text']->value,'_menu_icon'=>$_smarty_tpl->tpl_vars['menu_icon']->value,'lock'=>'y','fileId'=>$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['fileId'],'galleryId'=>$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['galleryId']), $_block_content, $_smarty_tpl, $_block_repeat);  } array_pop($_smarty_tpl->smarty->_tag_stack);?>
<?php }?><?php }?><?php }?><?php }?><?php if ($_smarty_tpl->tpl_vars['prefs']->value['feature_webdav']=='y'){?><?php $_smarty_tpl->tpl_vars['virtual_path'] = new Smarty_variable(smarty_modifier_virtual_path($_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['fileId']), null, 0);?><?php if ($_smarty_tpl->tpl_vars['prefs']->value['feature_file_galleries_save_draft']=='y'){?><?php $_smarty_tpl->smarty->_tag_stack[] = array('self_link', array('_icon'=>"tree_folder_open",'_menu_text'=>$_smarty_tpl->tpl_vars['menu_text']->value,'_menu_icon'=>$_smarty_tpl->tpl_vars['menu_icon']->value,'_script'=>"javascript:open_webdav('".((string)$_smarty_tpl->tpl_vars['virtual_path']->value)."')",'_noauto'=>"y",'_ajax'=>"n")); $_block_repeat=true; echo smarty_block_self_link(array('_icon'=>"tree_folder_open",'_menu_text'=>$_smarty_tpl->tpl_vars['menu_text']->value,'_menu_icon'=>$_smarty_tpl->tpl_vars['menu_icon']->value,'_script'=>"javascript:open_webdav('".((string)$_smarty_tpl->tpl_vars['virtual_path']->value)."')",'_noauto'=>"y",'_ajax'=>"n"), null, $_smarty_tpl, $_block_repeat);while ($_block_repeat) { ob_start();?>
Open your draft in WebDAV<?php $_block_content = ob_get_clean(); $_block_repeat=false; echo smarty_block_self_link(array('_icon'=>"tree_folder_open",'_menu_text'=>$_smarty_tpl->tpl_vars['menu_text']->value,'_menu_icon'=>$_smarty_tpl->tpl_vars['menu_icon']->value,'_script'=>"javascript:open_webdav('".((string)$_smarty_tpl->tpl_vars['virtual_path']->value)."')",'_noauto'=>"y",'_ajax'=>"n"), $_block_content, $_smarty_tpl, $_block_repeat);  } array_pop($_smarty_tpl->smarty->_tag_stack);?>
<?php }else{ ?><?php $_smarty_tpl->smarty->_tag_stack[] = array('self_link', array('_icon'=>"tree_folder_open",'_menu_text'=>$_smarty_tpl->tpl_vars['menu_text']->value,'_menu_icon'=>$_smarty_tpl->tpl_vars['menu_icon']->value,'_script'=>"javascript:open_webdav('".((string)$_smarty_tpl->tpl_vars['virtual_path']->value)."')",'_noauto'=>"y",'_ajax'=>"n")); $_block_repeat=true; echo smarty_block_self_link(array('_icon'=>"tree_folder_open",'_menu_text'=>$_smarty_tpl->tpl_vars['menu_text']->value,'_menu_icon'=>$_smarty_tpl->tpl_vars['menu_icon']->value,'_script'=>"javascript:open_webdav('".((string)$_smarty_tpl->tpl_vars['virtual_path']->value)."')",'_noauto'=>"y",'_ajax'=>"n"), null, $_smarty_tpl, $_block_repeat);while ($_block_repeat) { ob_start();?>
Open in WebDAV<?php $_block_content = ob_get_clean(); $_block_repeat=false; echo smarty_block_self_link(array('_icon'=>"tree_folder_open",'_menu_text'=>$_smarty_tpl->tpl_vars['menu_text']->value,'_menu_icon'=>$_smarty_tpl->tpl_vars['menu_icon']->value,'_script'=>"javascript:open_webdav('".((string)$_smarty_tpl->tpl_vars['virtual_path']->value)."')",'_noauto'=>"y",'_ajax'=>"n"), $_block_content, $_smarty_tpl, $_block_repeat);  } array_pop($_smarty_tpl->smarty->_tag_stack);?>
<?php }?><?php }?><?php if ($_smarty_tpl->tpl_vars['prefs']->value['feature_share']=='y'&&$_smarty_tpl->tpl_vars['tiki_p_share']->value=='y'){?><a href="tiki-share.php?url=<?php echo $_smarty_tpl->tpl_vars['tikiroot']->value;?>
<?php echo rawurlencode(smarty_modifier_sefurl($_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['id'],'file'));?>
"><?php echo smarty_function_icon(array('_menu_text'=>$_smarty_tpl->tpl_vars['menu_text']->value,'_menu_icon'=>$_smarty_tpl->tpl_vars['menu_icon']->value,'_id'=>'share_link','alt'=>"Share a link to this file"),$_smarty_tpl);?>
</a><?php }?><?php if ($_smarty_tpl->tpl_vars['prefs']->value['feature_tell_a_friend']=='y'&&$_smarty_tpl->tpl_vars['tiki_p_tell_a_friend']->value=='y'){?><a href="tiki-tell_a_friend.php?url=<?php echo $_smarty_tpl->tpl_vars['tikiroot']->value;?>
<?php echo rawurlencode(smarty_modifier_sefurl($_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['id'],'file'));?>
"><?php echo smarty_function_icon(array('_menu_text'=>$_smarty_tpl->tpl_vars['menu_text']->value,'_menu_icon'=>$_smarty_tpl->tpl_vars['menu_icon']->value,'_id'=>'email_go','alt'=>"Email a link to this file"),$_smarty_tpl);?>
</a><?php }?><?php if ($_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['perms']['tiki_p_admin_file_galleries']=='y'||(!$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['lockedby']&&(($_smarty_tpl->tpl_vars['user']->value&&$_smarty_tpl->tpl_vars['user']->value==$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['user'])||($_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['perms']['tiki_p_edit_gallery_file']=='y'&&$_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['perms']['tiki_p_remove_files']=='y')))){?><a href="tiki-list_file_gallery.php?remove=<?php echo $_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['fileId'];?>
&galleryId=<?php echo $_smarty_tpl->tpl_vars['files']->value[$_smarty_tpl->tpl_vars['changes']->value]['galleryId'];?>
"><?php echo smarty_function_icon(array('_menu_text'=>$_smarty_tpl->tpl_vars['menu_text']->value,'_menu_icon'=>$_smarty_tpl->tpl_vars['menu_icon']->value,'_id'=>'cross','alt'=>"Delete"),$_smarty_tpl);?>
</a><?php }?><?php if ($_smarty_tpl->tpl_vars['prefs']->value['javascript_enabled']=='y'){?><?php if ($_smarty_tpl->tpl_vars['menu_text']->value=='y'||$_smarty_tpl->tpl_vars['menu_icon']->value=='y'){?></form><?php }?><?php }?><?php }?><?php }} ?>